---
- name: This playbook create a file or dir
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Create a file
    file:
      path: /home/ansadmin/demofile
      state: touch

  - name: Create a directory
    file:
      path: /home/ansadmin/demodir1
      state: directory
