---
- name: This playbook installs the packages
  hosts: webservers
  become: true
  tasks:
  - name: Install the packge
    yum:
    #  name: [ 'git', 'make', 'gcc', 'wget', 'telnet', 'gzip']
      name: "{{ item }}"    
      state: installed
    with_items:
      - git
      - make
      - gcc
      - wget
      - telnet
      - gzip     

