---
- name: Setup tomcat
  hosts: all
  become: true
  tasks:
  - name: Install Java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install Java on Ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"


  - name: Download  tomcat packages
    get_url:
      url: https://mirrors.koehn.com/apache/tomcat/tomcat-8/v8.5.59/bin/apache-tomcat-8.5.59.tar.gz
      dest: /opt

  - name: Untar the tomcat gzip
    unarchive:
      src: /opt/apache-tomcat-8.5.59.tar.gz
      dest: /opt
      remote_src: yes

  - name: add execution permission on startup.sh file
    file:
      path: /opt/apache-tomcat-8.5.59/bin/startup.sh
      mode: 0777

  - name: Start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.59/bin
  
