---
- name: This playbook to uninstall httpd
  hosts: webservers
  become: true
  tasks:
  - name: Stop the httpd service
    service:
      name: httpd
      state: stopped
  
  - name: Uninstall the httpd pkg
    yum:
      name: httpd
      state: absent
